### ISSUE TITLE
overlaping episode title in main view

### ISSUE THREAD

**Issue by vankasteelj** [vankasteelj/frak#141]
![Frak_IKxQreQexl](https://user-images.githubusercontent.com/12599850/157336652-d91aa315-c177-43cd-ab53-dd8cdcfe1d0f.jpg)

**Comment by JourneyOver** [comment]
Sorry I know this isn't the correct place to ask (should probably just make a new issue or something) but is this app still being worked on? as the last update to the repo (and last update to the application) seems to be october of last year.
