### ISSUE TITLE
Freeze upon picking magnet file

### ISSUE THREAD

**Issue by Reitann** [vankasteelj/frak#160]
Picking a magnet link from the list after choosing show/movie will often make the app freeze after a second or two, requiring app restart (ending task). MPV does not have time to launch before freeze, although sometimes it can appear as a subprocess of Frak in task manager. Happens almost exclusively on files with many peers/seeders.

Local files do not have the same issue, at least I can't reproduce it with local files.

Event Viewer shows two different errors, Event ID 1000(100) and Event ID 1002(101).

**Event ID 1000(100) error:**
```
Faulting application name: Frak.exe, version: 0.64.1.0, time stamp: 0x5f7956d0
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1706, time stamp: 0x458acb5b
Exception code: 0xc06d007f
Fault offset: 0x0000000000034fd9
Faulting process id: 0x240
Faulting application start time: 0x01d87788003f3d85
Faulting application path: C:\Program Files\Frak\Frak.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 5920f90a-5317-45f4-bfcc-7cabb8ab0112
Faulting package full name: 
Faulting package-relative application ID: 
```

**Event ID 1002(101) error:**
```
The program Frak.exe version 0.64.1.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 40e8
 Start Time: 01d87787db4e6ec4
 Termination Time: 4294967295
 Application Path: C:\Program Files\Frak\Frak.exe
 Report Id: aefa0166-3cf2-468b-b1f5-29f6d1b8cd9d
 Faulting package full name: 
 Faulting package-relative application ID: 
 Hang type: Top level window is idle

```
**Specs/Info**
_Frak version 1.12.0
OS: W10, 21H2 build 19044.1706
CPU: i7-3820
GPU: gtx 960 4gb
RAM: 16gb DDR3 @1333Mhz_

Let me know if there is anything else I can provide!

**Comment by vankasteelj** [comment]
I've encountered the same issue, it's most probably due to webtorrent, the engine used to download from P2P protocols. I'm gonna report the issue to the developers and probably go back to an earlier version of their engine in the meantime, it's slower but afaik doesn't "freeze" the process.
