### ISSUE TITLE
Frak won't load after 1.22

### ISSUE THREAD

**Issue by leppic** [vankasteelj/frak#212]
Since updating to 1.22 Frak won't load. The program opens, but that's it. It's just a window with a black background (dark mode). I think it's supposed to login to Trakt at this point.  I've updated from 1.21 (not sure).  I can't open the console. so don't know how to debug any further.

Win Version 22H2 (OS Buld 19045.3086)

**Comment by leppic** [comment]
Just reverted to 1.21 and the same issue. I feel like it's a Trakt issue. Will check tomorrow again

**Comment by vankasteelj** [comment]
You might want to use the uninstaller to remove all leftovers and check in `%localappdata%` and `%appdata%` (just paste this in your file explorer) if all "nwjs" or "frak" folders are removed. Then install it fresh.
