### ISSUE TITLE
I'm watching you

### ISSUE THREAD

**Issue by jaruba** [vankasteelj/frak#55]
![522](https://user-images.githubusercontent.com/1777923/47559308-d8d64480-d91d-11e8-8113-4d226361f378.gif)

**Comment by vankasteelj** [comment]
Y u do dis

**Comment by jaruba** [comment]
because I CARE!

![200](https://user-images.githubusercontent.com/1777923/47560368-af6ae800-d920-11e8-9757-7ce48717555e.gif)

**Comment by jaruba** [comment]
but, as long as i'm here, i care and don't want this to be just a pollutant for your issues, here be my 2 cents:

- use jackett for torrents, that shit's awesome
- slap a web server in this baby so you can use it through the browser too, not just NW.js (you could just give the torrent stream link in the browser, or better yet a link for a m3u playlist with all the torrent's stream links)

**Comment by vankasteelj** [comment]
jackett doesnt seem to be javascript, and I'm still not a good enough developer to get away with anything but js.

using it in the browser isnt the goal, but I was wanting to use a webserver to allow sharing files between computers on the same network

**Comment by jaruba** [comment]
> jackett doesnt seem to be javascript

jackett isn't a js module, no. it's an application that you run locally, enable all the torrent sites you like in it (it has literally all the torrent sites, national ones too, private and public sites), and then it turns all of those sites into APIs that you can use in any other application (as long as you give that application your jackett api key)

you can check out js implementations of attaching to the jackett APIs:
https://github.com/jaruba/PowderWeb/blob/master/server/jackett.js
https://github.com/BoredLama/stremio-jackett-addon

this will lead to a lot more torrents, better seeded ones too, you'd even find older torrents that still have seeds if you enable enough sites on it.

and you can always fallback on your current torrent search implementation in case a jackett api key hasn't been added in your app.

> using it in the browser isnt the goal

i get that, the difference between your app being browser compatible or not is relatively small though, as you can load it in NW.js too from a URL and have a module check if it's NW.js or not so it has different behavior as an app then in the browser. it's good practice to make it browser compatible from the get go, and better UX then just starting a webserver for sharing files instead of having your whole UI working on any device through the browser

trust me, i'm giving you good ideas here, whether or not you choose to use them is your choice though

your app looks good, glad to see your still building stuff, keep it up :)

**Comment by vankasteelj** [comment]
I get all that, but I have neither the time nor the knowledge to make big stuff happen. 

This app is basically an ugly trakt+webtorrent+mpv interfacer written in jquery and plain html. It is the definition of bad practice, but it works (meh, good enough anyway). I'd be willing to switch to something else if that existed, but I havent found anyone making precisely what I expect, so I kinda was obligated to make it myself^^

Maybe one day i'll grow a pair and start making good code, but until then, I'm mostly focused on "making things happen for me" :)

**Comment by jaruba** [comment]
years ago when we talked you were doing the same thing, different UI and name though :))

i've been working on something new lately, called Powder Web:
https://github.com/jaruba/PowderWeb

it has no internal player, but can be hooked up to any player.. the UI is more of a torrent client's, but the app itself can be used as a backbone for any other UI, serves APIs for everything (finding subtitles, searching on Jackett, etc), can be connected to Jackett, AceStream, SopCast, etc.

it's still in it's infancy though, maybe when i get it in a more stable state, we can work on a catalog ui for movies and series together based on it, if you want to and have the time for it

this would get you the UI you always wanted without the hassle of keeping the backend updated and working, as that would be Powder Web and it would do all the heavy lifting, so you could just focus and how you want it to look and act without worrying about possible deprecation

just (another) idea though
