### ISSUE TITLE
Mark already watched as watched

### ISSUE THREAD

**Issue by Rizwan-Qamar** [vankasteelj/frak#89]
Already watched movie is giving an option to "Mark as watched"

![image](https://user-images.githubusercontent.com/1522223/66548598-89b01080-eb7c-11e9-8e3a-62dcbd90a3da.png)
![image](https://user-images.githubusercontent.com/1522223/66548655-a64c4880-eb7c-11e9-9654-e41bfb96818e.png)

**Comment by vankasteelj** [comment]
Thanks, i'll check that when I have time

**Comment by vankasteelj** [comment]
Ok, i'm not going to do anything because you can watch a movie multiple times.
