### ISSUE TITLE
Change default player

### ISSUE THREAD

**Issue by NocFA** [vankasteelj/frak#97]
Hello,

I use SVP 4 for high framerate playback, I'd love to be able to choose my own player to launch with so I can hook SVP or somehow implement native compatibility (which shouldn't be too hard as SVP is directly compatible with MPV with some tweaking) via some sort of toggle switch for users.

Thanks! :)

**Comment by vankasteelj** [comment]
Everything in this app is build for and around MPV. If it doesn't work as it with SVP4, I won't make any changes here, more so because it is a commercial product not complying with open-source standards.
